CREATE SCHEMA CLUBE_DO_LIVRO;
 
CREATE TABLE LIVROS  (
ID_LIVRO INT NOT NULL,
NOME_LIVRO VARCHAR(100) NOT NULL,
AUTORIA VARCHAR(100) NOT NULL,
EDITORA VARCHAR(100) NOT NULL,
CATEGORIA VARCHAR(100) NOT NULL,
PREÇO DECIMAL(5,2) NOT NULL,


primary key(ID_LIVRO)
);

CREATE TABLE ESTOQUE (
ID_LIVRO INT NOT NULL,
QTD_ESTOQUE INT NOT NULL,

PRIMARY KEY (ID_LIVRO)
);

CREATE TABLE VENDAS (
ID_PEDIDO INT NOT NULL,
ID_VENDEDOR INT NOT NULL,
ID_LIVRO INT NOT NULL,
QTD_VENDIDA INT NOT NULL,
DATA_VENDA INT NOT NULL,

PRIMARY KEY (ID_PEDIDO, ID_VENDEDOR)
);

CREATE TABLE VENDEDORES (
    ID_VENDEDOR INT NOT NULL,
	NOME_VENDEDOR VARCHAR(255) NOT NULL,
PRIMARY KEY (ID_VENDEDOR)
);

SET FOREIGN_KEY_CHEKS = 0;

INSERT INTO LIVROS VALUES
(1, 'O Senhor dos Anéis', 'J.R.R. Tolkien', 'HarperCollins', 'Fantasia', 59.90),
(2, '1984', 'George Orwell', 'Companhia das Letras', 'Ficção Científica', 39.90),
(3, 'Dom Casmurro', 'Machado de Assis', 'Principis', 'Literatura Brasileira', 29.90),
(4, 'A Revolução dos Bichos', 'George Orwell', 'Companhia das Letras', 'Sátira', 35.50),
(5, 'O Hobbit', 'J.R.R. Tolkien', 'HarperCollins', 'Fantasia', 49.90); 

SELECT * FROM LIVROS;